version: '3.8'
services:
  snappy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Snappy
    restart: always
    ports:
      - 3000:3000
    expose:
      - 3000
    env_file:
      - .env
